# Rutas de directorios
RAW_FILES_PATH = '../data/raw_data'
CLASSIFIED_FILES_PATH = '../data/classified_data'
SENSOR_DIR = '/sensores/'
PLUVIOMETER_DIR = '/pluviometro/'
SENSOR_FILES_DIRECTORY = RAW_FILES_PATH + SENSOR_DIR
PLUVIOMETER_FILES_DIRECTORY = RAW_FILES_PATH + PLUVIOMETER_DIR
CLASSIFIED_SENSOR_PATH = CLASSIFIED_FILES_PATH + SENSOR_DIR
CLASSIFIED_PLUVIOMETER_PATH = CLASSIFIED_FILES_PATH + PLUVIOMETER_DIR
